version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - ./data:/app/data

  #frontend:
  #  build: ./frontend
  #  ports:
  #    - "8501:8501"
  #  env_file: .env

  postgres:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: dssuser
      POSTGRES_PASSWORD: dsspass
      POSTGRES_DB: dssdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  pgdata:
